### ISSUE TITLE
Payment status

### ISSUE THREAD

**Issue by eric-fahendrena** [anurag-2024/SharpSkill#8]
It is necessary to be transparent about how **to set payment status**. In `Booking model`, there is a field for payment status but I think there is no reason to set payment status with Bookings api. On the other hand, `Payment model` is, I think, the best and the only model that should have payment status setting feature.

However, Booking api can verify the payment status but it could not set it.

What do you think?

**Comment by anurag-2024** [comment]
Yes, you are right Payment status of bookings can managed by Payment model. So remove it from Bookings Model.
